#!/usr/bin/env bash
set -euo pipefail

# Resolve the repository root from the script location so cleanup stays local.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$script_dir"

removed=0

# Remove repo-local state generated by the launcher scripts, Apptainer,
# and interactive shells started inside the container.
while IFS= read -r path; do
  rm -rf -- "$path"
  printf 'Removed %s\n' "$path"
  removed=1
done < <(
  find "$repo_root" \
    \( -type d -name '.apptainer-home' -o -type f -name '.bash_history' \) \
    -print
)

# Report when there was nothing to clean so the caller gets explicit feedback.
if [[ "$removed" -eq 0 ]]; then
  echo "No generated temporary files found under $repo_root"
fi
